sudo: false

before_install: gem install bundler

rvm:
  - 1.8
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head

script: bundle exec rspec spec